### ISSUE TITLE
Underlying Wasm runtime, wasmer -> wasmtime

### ISSUE THREAD

**Issue by brooksmtownsend** [tessi/wasmex#336] opened 2022-06-09 20:17 UTC
Slightly related to #282 

So wasmer is the underlying runtime at the moment for wasmex, would you consider switching the underlying runtime of this project to wasmtime like https://github.com/viniarck/wasmtime-ex has?

We've loved using this project and are looking to take advantage of the features that come first to wasmtime, and in a perfect world this would be done through swappable runtimes like #282. In the shorter term, is there any reservation to changing the runtime?

Thanks @tessi 🚀

**Comment by tessi** [comment] 2022-06-10 06:27
Thanks for asking! 💜 
I would love to have wasmtime as the first other engine. I even have a local fork porting wasmex to wasmtime - I think having a fork is the first step to figure out the differences we need to be aware of when implementing #282

The only problem is my limited free time. Do you have the time to take over and/or help here?

**Comment by tessi** [comment] 2022-07-27 21:40
Hey @brooksmtownsend 👋 
sorry for letting you hang so long. But I have mildly good news for a wasmtime fork of wasmex. I used some of my vacation time to get my fork working enough to make it public.
Please find it [here](https://github.com/tessi/wasmex-wasmtime).

It turned out to be a way bigger refactoring than anticipated and, unfortunately, it is not fully working at the moment. This is where I could really use some of your help :)

* the biggest issue right now is a deadlock where I am not sure how to solve it best. The reason is that wasmtime needs a `store` (a place that hold memory for WASM instances/modules) for almost all API calls. I added elixir APIs to create new stores so that we can pass down the store to all wasm calls. The problem is that we need to place the store (on the rust side) behind a mutex to make it thread safe. Now, when calling a WASM function we hold a mutex-lock on the store. When that WASM function call requires a callback (an elixir func being executed), that elixir function callback needs the same store for many API calls - e.g. manipulating WASM memory. But these API calls fail since we cannot unlock the mutex again. It's hard to explain, but there is [a test](https://github.com/tessi/wasmex-wasmtime/blob/0e58b83ce897f982f44fff47b2f5f2b0a46b4877/test/wasmex_wasmtime_test.exs#L124) that runs this scenario  and results in the described deadlock. If you could solve that (and I don't know how exactly yet) that would be huge
* I haven't tested (or fixed tests for) WASI support yet. The same probably applies for other areas (std in/out/err, pipes).
* docs are blindly copied from wasmex and are half-wrong after the refactoring

**Comment by tessi** [comment] 2022-08-04 07:15
Regarding the store-deadlock problem, I just realized that our wrapped functions receive a [Caller](https://github.com/bytecodealliance/wasmtime/blob/ca3947911eebeadc2f5f0dfeedb9e2357d9231f1/crates/wasmtime/src/func.rs#L1495) which happens to implement `AsContextMut`/`AsContext` and can act like a `Store` when called within the function scope.

I think we need to find a way to extract [this caller](https://github.com/tessi/wasmex-wasmtime/blob/59703ca046e988a239ac5b4c76c2707b4b38a40f/native/wasmex_wasmtime/src/environment.rs#L107) into the elixir fn callback_context [that we create here](https://github.com/tessi/wasmex-wasmtime/blob/59703ca046e988a239ac5b4c76c2707b4b38a40f/native/wasmex_wasmtime/src/environment.rs#L147).If we have that done, we could pass the caller (acting as a store) instead of the original deadlocked store.
I stumbled across lifetime issues when attempting that, but maybe you can figure out a way to forward the `Caller` to Elixir somehow?

**Comment by tessi** [comment] 2022-08-04 07:17
Maybe we can get inspiration from wasmtime-py, they interface the C API, but they do exactly what I proposed above. [They take the caller and pass them as a reference to the python function](https://github.com/bytecodealliance/wasmtime-py/blob/8702823b61227388de3b6a27e82eb9b0cbde8dd8/wasmtime/_func.py#L178). I guess they can get around lifetime issues since C doesn't have lifetimes :D but maybe there is a (unsafe?) Rust way to do similar.

**Comment by brooksmtownsend** [comment] 2022-08-11 15:20
Thank you for the great updates @tessi, I'm following along here but haven't had much free time to look into it yet

**Comment by tessi** [comment] 2022-08-12 13:07
no worries. I'm in the same boat :)

**Comment by tessi** [comment] 2022-08-31 08:15
Ok, I _think_ i can report progress. I just pushed another (still very broken) version of wasmex-wasmtime which introduces a new concept

* during function execution we get the `caller` struct passed from wasmtime, that caller is only valid during function execution and can not safely be passed into elixir land because of lifetimes
* I introduced a "caller registry" where you can store a caller reference (using an `unsafe` pointer hack) and get a "token" back. That token can be passed up into elixir land. We wrap that token into a `StoreOrCaller` struct because stores and callers can be passed interchangeably into many function (e.g. Memory.read).
* from elixir you can now use that `StoreOrCaller` within a function call to read/write memory (or do other things where you'd normally need a store) without running into deadlocks.

So far for the theory :D In practise, when doing the above, wasmtime panics because it thinks we're using a different store somehow and I don't know why yet.

I added some debug code [here](https://github.com/tessi/wasmex-wasmtime/blob/4410d69298f00d9b6b15b98e99282f1b7618a2a2/native/wasmex_wasmtime/src/environment.rs#L1799) which illustrates the problem and pointer-hack, but simplifies it as much as possible :)

Within a wrapped function, I can read memory using the originally provided `caller`:

```rust
let mut buffer = [0];
memory.read(&caller, 0, &mut buffer).unwrap();
println!("buffer 1: {:?}", buffer);
```

however, after doing a horrible unsafe pointer hack - which should give us the same caller because we read from the same memory address - we get a panic:

```rust
let raw_ptr: *mut Caller<StoreData> = &mut caller as *mut Caller<StoreData>;
let the_other_caller: &mut Caller<StoreData> = unsafe { &mut *raw_ptr as &mut Caller<StoreData> };

memory.read(the_other_caller, 0, &mut buffer).unwrap();
println!("buffer 2: {:?}", buffer);

// thread '<unnamed>' panicked at 'object used with the wrong store',
// /Users/tessi/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-0.39.1/src/store/data.rs:258:5
```

you can play with that scenario, when checking out `main` and running `RUST_BACKTRACE=1 mix test test/wasmex_wasmtime_test.exs:125`

I hope someone here can help me find out why wasmtime thinks this is a new/different store and maybe even fix the problem :)

**Comment by tessi** [comment] 2022-09-01 19:38
Good news! together with @hamptokr we could fix the memory problem and reading/writing memory from within function calls now fully works. In fact, all tests - with the exception of WASI tests as I didn't look at WASI yet - work \o/

Next up: Fixing WASI and cleaning things up

**Comment by tessi** [comment] 2022-09-05 19:50
Keeping you updated here: WASI seems to work roughly - I still have to fix file access permissions, but 5/10 wasi tests work. This is getting closer :)

**Comment by brooksmtownsend** [comment] 2022-09-21 18:06
Perfect timing here, Wasmtime just announced 1.0! Very exciting 😄

**Comment by tessi** [comment] 2022-10-06 16:52
super exciting indeed! :)

I worked some more on the wasmtime fork and all test are green now 🎉  However, it works only on [my wasmtime fork](https://github.com/tessi/wasmtime). Next task is to contribute my wasmtime changes back so we can have proper access permissions for preopened directories.

**Comment by tessi** [comment] 2022-10-06 16:53
However, @brooksmtownsend I'd love if you could give that fork a try and see if it works for you

**Comment by tessi** [comment] 2022-12-30 00:22
> Next task is to contribute my wasmtime changes back so we can have proper access permissions for preopened directories.

Turns out that [the wasmtime folks recommended to now have access permissions for WASI preopens yet](https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/.E2.9C.94.20WASI.20preopen.20directories.20with.20capabilities/near/302709679) but rather wait it to be implemented "proper" in the future ([ticket](https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/.E2.9C.94.20WASI.20preopen.20directories.20with.20capabilities/near/302709679)).

So I removed use of my custom wasmtime fork and instead upgraded to wasmtime 4.0.

In addition I moved all WASI opts (but especially the directory preopen options) into proper Elixir structs. This makes it easier to upgrade them in the future was users of wasmex will get proper compile-time errors when missing keys (e.g. for access permissions).

**Comment by tessi** [comment] 2022-12-30 00:24
@brooksmtownsend did you have the time to try things out yet? No worries if not :)

I'll soon merge my work back into this repo (in some dev-branch, I guess) to prepare docs, polish, and release the new version

**Comment by tessi** [comment] 2023-01-02 09:17
The [MR that brings the changes back](https://github.com/tessi/wasmex/pull/385) is here and looks good. Docs are updated, changelog is written.

**Comment by tessi** [comment] 2023-01-03 09:54
Alright, merged the MR 🚢

**Closed by tessi** 2023-01-03 09:54 UTC
