### ISSUE TITLE
consume_fuel function example does not work as expected

### ISSUE THREAD

**Issue by kimjarvis** [tessi/wasmex#407] opened 2023-02-13 16:43 UTC
The [consume_fuel function example](https://hexdocs.pm/wasmex/Wasmex.EngineConfig.html#consume_fuel/2) does not behave as expected.

I expected `config.consume_fuel` to return true, as described.  Instead,  the function returned false.

```
iex(1)> config = %Wasmex.EngineConfig{}
%Wasmex.EngineConfig{
  consume_fuel: false,
  cranelift_opt_level: :none,
  wasm_backtrace_details: false
}
iex(2)>  |> Wasmex.EngineConfig.consume_fuel(true)
%Wasmex.EngineConfig{
  consume_fuel: true,
  cranelift_opt_level: :none,
  wasm_backtrace_details: false
}
iex(3)> config.consume_fuel
false
```

Similarly, [wasm_backtrace_details](https://hexdocs.pm/wasmex/Wasmex.EngineConfig.html#wasm_backtrace_details/2) does not return the expected value.

```
iex(1)> config = %Wasmex.EngineConfig{}
%Wasmex.EngineConfig{
  consume_fuel: false,
  cranelift_opt_level: :none,
  wasm_backtrace_details: false
}
iex(2)> |> Wasmex.EngineConfig.wasm_backtrace_details(true)
%Wasmex.EngineConfig{
  consume_fuel: false,
  cranelift_opt_level: :none,
  wasm_backtrace_details: true
}
iex(3)> config.wasm_backtrace_details
false
```

**Comment by tessi** [comment] 2023-04-10 21:41
Hey @kimjarvis I believe it's the way you use the Elixir REPL that makes it _look_ like a bug.

You actually execute three different expressions (instead of the two you probably expect):

1. `config = %Wasmex.EngineConfig{}` create a default EngineConfig and save it in the `config` variable
2. `|> Wasmex.EngineConfig.consume_fuel(true)` take the last result and pipe it into `consume_fuel/2`. The result is printed and then discarded -- the `config` variable *is not* updated
3. `config.consume_fuel` access the `consume_fuel` field of the `config` struct created in step 1.

The code (with newline) works in elixir files (.ex/.exs) but not so well in the Elixir REPL because the REPL interprets newlines as a command to execute all things so far. You could work around this by re-assigning `config` on line two, for example:

```
iex(1)> config = %Wasmex.EngineConfig{}
iex(2)> config = Wasmex.EngineConfig.consume_fuel(config, true)
iex(3)> config.consume_fuel
true
```

I'll close this issue, because this is not a bug in Wasmex (and maybe an irritating thing in Elixir core/REPL). Please feel free to re-open the issue if you believe otherwise.

**Closed by tessi** 2023-04-10 21:41 UTC
